### ISSUE TITLE
JOSS Review TODO

### ISSUE THREAD

**Issue by mcbrider5002** [sdrogers/vimms#235]
An itemised checklist of issues to address raised by JOSS reviewers.

- [x] Community guidelines for how to contribute/report issues with the software/seek support not linked in documentation/README.
  Comments: Added a new section 'Contributing' in the README with a link to CONTRIBUTING.md
- [x] README when mentioning example notebooks should link them. Specifically in `https://github.com/glasgowcompbio/vimms/blob/master/docs/README.md`.
  Comments: Added the links under 'Example Codes and Documentations'
- [x] Example notebooks do not run on the current version of ViMMS. Potential need for clear instructions on how to access the tagged version of the repository, and which version. 
  Comments: we've made sure that all the notebook now run on the current version of ViMMS.
- [x] Which parts of the API are meant to be public-facing are not clear. Reviewer comments in particular that usage of Python naming conventions for access modifiers are inconsistent.
  Comments: we'll improve this over time
- [x] Need for in-code documentation (i.e. docstrings). In particular the reviewer cites the need for parameter documentation.
  Comments: documentation exists at https://vimms.readthedocs.io/, but it will be improved over time 
- [x] Instances of `from library import *` considered bad practise. Reviewer highlights examples in notebooks.
  Comments: got rid of `import *` in the codes and all notebooks. 
- [x] Test fixtures should have a README explaining how to generate them, and be removed from the repo to be generated/cached during the testing process.
  Comments: a README file has been added to https://github.com/glasgowcompbio/vimms/tree/master/tests/fixtures.
- [x] Codecov report should be added to CI https://github.com/glasgowcompbio/vimms/blob/master/.github/workflows/python-package.yml#L37
  Comments: code coverage report has been added
- [x] Contributor guidelines should mention what linter/checking/testing framework to use when contributing. Particularly, is the code meant to be flake8 compliant, despite the many violations?
  Comments: We've fixed codes to be PEP8-compliant. In the contributor guideline (CONTRIBUTING.md), we now mention what linter/testing/documentation frameworks are used when contributing.
- [x] References to the GitHub repository still point to the old address registered under Simon, rather than GlasgowCompBio. Reviewer highlights examples in instructions for how to clone repository, and in `setup.py`.
  Comments: fixed.
- [x] Python 2 has reached EOL, and therefore it is not necessary to specify that Python 3 is required.
  Comments: removed the mention of Python 2 from the README

- [x] In `create_if_not_exist`, an empty path will return `.exists() == True`, so it's not necessary to check that path length is >0 to inform the user when a directory is created. 
  Comments: fixed in https://github.com/glasgowcompbio/vimms/commit/89e9da5df33c76fa8927c4503cef335178b157e4
- [x] `load_obj` should throw an error rather than a warning and returning None if the pickle can't be opened.
  Comments: fixed in https://github.com/glasgowcompbio/vimms/commit/89e9da5df33c76fa8927c4503cef335178b157e4
- [x] `chromatogramDensityNormalisation` could check if the rts/mzs are the same length.
  Comments: fixed in https://github.com/glasgowcompbio/vimms/commit/89e9da5df33c76fa8927c4503cef335178b157e4
- [x] `from tqdm.auto import tqdm` could replace tqdm import to better handle progress bars on different platforms.
  Comments: done in https://github.com/glasgowcompbio/vimms/commit/a63a9687fff50f4f43d1b45230f5257401dc636a
- [x] The multi-sample methods notebook folder inside demo is empty.
  Comments: I'm assuming this is because we haven't written them yet. Removed that folder for now: https://github.com/glasgowcompbio/vimms/commit/7d5a2df30965bc3cf606a775ac0d949416845d51.
- [x] Reviewer questions need for vimms/notebook to be inside the package itself.
  Comments: that shouldn't be there. The notebook inside has been moved to the `experimental` folder in this commit https://github.com/glasgowcompbio/vimms/commit/1114c1827d1fd46c789ca6072675bc2915c52ca4.
- [X] Controller and agent classes should use abstract methods instead of raising `NotImplementedError` so failure happens during instantiation rather than during execution.
  Comments: we've properly implemented these abstract methods in https://github.com/glasgowcompbio/vimms/commit/64fcfe769d03ff9c8755eb05ed9e72d10d85c0a2 and https://github.com/glasgowcompbio/vimms/commit/4cbfe5544cc8b86c9c791b5fa8867a07f2497a29
- [x] `NotImplementedError()`s should be raised with the `raise` keyword. Reviewer points to specific example in `Controller/vinny_test`
  Comments: Have removed `Controller/vinny_test` in https://github.com/glasgowcompbio/vimms/commit/ef78bb78f988c98fde4913facc52f8c6724d73cc since it's unused.
- [x] `old_unused_experimental` should be moved into another branch or deleted.
  Comments: all the experimental stuff have been moved to `old_unused_experimental` branch.
- [x] `self.C12_proportion = 0.989` in Chemicals should live inside `vimms.Common`.
  Comments: tidied up constants in https://github.com/glasgowcompbio/vimms/commit/45b858ca352483a364d04ca5218121a73ce5e58a
